//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationFormMvcEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Moblie_Number { get; set; }
        public string Email_id { get; set; }
        public string Password { get; set; }
        public string Conform_Password { get; set; }
        public int Age { get; set; }
        public string Gender { get; set; }
        public System.DateTime Date_of_Birth { get; set; }
        public string Course { get; set; }
        public System.DateTime Registration_Date { get; set; }
    }
}
